// open-api-editor-ui/src/components/inputs/TextInput.vue
<template>
  <div>
    <div class="mb-1 w-full flex justify-between">
      <label
        :for="escapedLabel"
        class="block text-sm font-medium leading-5 text-gray-700"
        >{{ label }}</label
      >
      <div
        v-if="isOptional"
        class="block text-sm font-medium leading-5 text-gray-600"
      >
        Optional
      </div>
    </div>
    <div class="relative rounded-md shadow-sm">
      <input
        :id="escapedLabel"
        class="block appearance-none w-full bg-white border border-gray-400
          hover:border-gray-500 px-3 py-2 rounded leading-tight
          focus:outline-none focus:shadow-outline"
        :placeholder="placeholder"
        :aria-describedby="escapedLabel + '-description'"
      />
    </div>
    <p
      v-if="description"
      class="mt-2 text-sm text-gray-500"
      :id="escapedLabel + '-description'"
    >
      {{ description }}
    </p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "TextInput",

  props: {
    label: { type: String, required: true },
    placeholder: String,
    description: String,
    isOptional: Boolean
  },

  computed: {
    escapedLabel(): string {
      return this.label.toLowerCase();
    }
  }
});
</script>

// site/src/components/inputs/TextInput.tsx
type Props = {
  value: string;
  label: string;
  placeholder: string;
  id: string;
  isOptional: boolean;
};

const TextInput = (props: Props) => {
  return (
    <div>
      <div className="mb-1 w-full flex justify-between">
        <label
          className="block font-medium leading-5 text-gray-700"
          htmlFor={props.id}
        >
          {props.label}
        </label>
        <span className="block text-sm font-medium leading-5 text-gray-600">
          {props.isOptional ? "Optional" : ""}
        </span>
      </div>
      <div className="relative rounded-xl shadow-sm">
        <input
          className="block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-3 py-2 rounded-xl leading-tight focus:outline-none focus:shadow-outline"
          type="text"
          name={props.id}
          id={props.id}
          placeholder={props.placeholder}
        />
      </div>
    </div>
  );
};

export default TextInput;
