// archive/site/src/components/editor/paths/Paths.tsx
import Button from "../../buttons/Button"
import Path from "./Path"

type Props = {
  className?: string
}

const Paths = (props: Props) => {
  return (
    <section className={"" + props.className}>
      <header className="mb-2 flex flex-row justify-between">
        <h2 className="text-xl font-medium text-gray-900" id="paths">
          Paths
        </h2>
        <Button role="secondary" action={() => {}}>
          Add Path
        </Button>
      </header>
      <div className="w-full flex flex-cols gap-4">
        <Path />
      </div>
    </section>
  )
}

export default Paths

// open-api-editor-ui/src/components/slots/Paths.vue
<template>
  <section class="m-1 sm:m-0">
    <div class="z-10 mb-2 pt-4 sticky top-0 bg-white bg-opacity-75">
      <div class="container mx-auto flex justify-between">
        <h2 class="text-xl">Paths</h2>
        <button
          @click="addPath"
          class="px-3 py-2 rounded-lg block font-medium leading-5 text-gray-900 bg-indigo-200 hover:bg-indigo-300"
        >
          Add path
        </button>
      </div>
    </div>
    <div class="mb-4 container mx-auto grid gap-4 grid-cols-2">
      <slot />
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Paths",

  methods: {
    addPath() {
      console.log("Not implemented");
    }
  }
});
</script>
