// site/src/components/editor/servers/Servers.tsx
import Button from "../../buttons/Button"

type Props = {
  className?: string
}

const Servers = (props: Props) => {
  return (
    <section className={"" + props.className}>
      <header className="flex flex-row justify-between">
        <h2 className="text-xl font-medium text-gray-900" id="servers">
          Servers
        </h2>
        <Button role="secondary" action={() => {}}>
          Add Server
        </Button>
      </header>
      <div className="grid"></div>
    </section>
  )
}

export default Servers

// open-api-editor-ui/src/components/slots/Servers.vue
<template>
  <section>
    <div class="mb-4 flex w-full justify-between">
      <h2 class="text-xl">Servers</h2>
      <button
        class="px-3 py-2 rounded-lg block font-medium leading-5 text-gray-900 bg-indigo-200 hover:bg-indigo-300"
      >
        Add server
      </button>
    </div>
    <slot />
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Servers"
});
</script>
